name: "CustomizableCombat"
version: ${project.version}
main: searous.customizableCombat.main.CustomizableCombat
api-version: "1.13"
commands:
  pvp:
    description: "Set local, and global PvP settings."
    usage: /pvp
permissions:
  customizable-combat.pvp.onoff:
    description: Gives access to /pvp <on/off>. Defaults to true
    default: true
  customizable-combat.pvp.players:
    description: Gives access to /pvp players <player> <on/off>
    default: op
  customizable-combat.pvp.global:
    description: Gives access to /pvp global <enabled/disabled> <on/off>
    default: op
  customizable-combat.pvp.check:
    description: Gives acces to /pvp check [player]. Defaults to true
    default: true